# Check out https://docs.codemagic.io/yaml/building-a-react-native-app/ for more information
# Please review and update values in curly braces

workflows:
    react-native:
        name: React Native App
        environment:
            vars:
                CM_KEYSTORE: Encrypted(Z0FBQUFBQmZhZktKTmJDRGpLbDBMVnlaVFFxaGJpR1ZsaWJyZVVjTkdfVVQ0cnpDMkkyMVNjNG1BeTlmcVRvOXZXb2ZENmJfaDRSOVY0U1dNNzg0ajFBNG9tVDBVTHlPQmc9PQ==)
                CM_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmZhZktKTmJDRGpLbDBMVnlaVFFxaGJpR1ZsaWJyZVVjTkdfVVQ0cnpDMkkyMVNjNG1BeTlmcVRvOXZXb2ZENmJfaDRSOVY0U1dNNzg0ajFBNG9tVDBVTHlPQmc9PQ==)
                CM_KEY_ALIAS_PASSWORD: Encrypted(Z0FBQUFBQmZhZktKTmJDRGpLbDBMVnlaVFFxaGJpR1ZsaWJyZVVjTkdfVVQ0cnpDMkkyMVNjNG1BeTlmcVRvOXZXb2ZENmJfaDRSOVY0U1dNNzg0ajFBNG9tVDBVTHlPQmc9PQ==)
                CM_KEY_ALIAS_USERNAME: Encrypted(Z0FBQUFBQmZhZktKTmJDRGpLbDBMVnlaVFFxaGJpR1ZsaWJyZVVjTkdfVVQ0cnpDMkkyMVNjNG1BeTlmcVRvOXZXb2ZENmJfaDRSOVY0U1dNNzg0ajFBNG9tVDBVTHlPQmc9PQ==)
            node: latest
        triggering:
            events:
                - push
                - tag
                - pull_request
            branch_patterns:
                - pattern: feature/dev_screens
                  include: true
                  source: true
        scripts:
            - name: install npm dependencies
              script: |
                npm install
            - name: Set Android SDK Location
              script: |
                echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            - name: Set up keystore
              script: |
                    echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
                    cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
                    storePassword=$CM_KEYSTORE_PASSWORD
                    keyPassword=$CM_KEY_ALIAS_PASSWORD
                    keyAlias=$CM_KEY_ALIAS_USERNAME
                    storeFile=/tmp/keystore.keystore
                    EOF
            - name: Build Android Release
              script: |
                # build Android
                cd android
                ./gradlew assembleDebug
            
        artifacts:
            - android/app/build/outputs/**/*.apk
        # publishing:
        #     email:
        #         recipients:
        #             williansoares.dev@gmail.com